export enum StoreStatus {
  WAITING_FOR_CREATE_APPROVE = 'WAITING_FOR_CREATE_APPROVE',
  REJECT = 'CREATE_REJECT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  WAITING_FOR_UPDATE_APPROVE = 'WAITING_FOR_UPDATE_APPROVE',
  WAITING_FOR_APPROVE_REJECT = 'WAITING_FOR_APPROVE_REJECT'

}