export enum ErrorType {
  BAD_TOKEN = 'BAD_TOKEN_ERROR',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED_ERROR',
  UNAUTHORIZED = 'AUTH_FAILURE_ERROR',
  ACCESS_TOKEN = 'ACCESS_TOKEN_ERROR',
  INTERNAL = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND_ERROR',
  NO_ENTRY = 'NO_ENTRY_ERROR',
  NO_DATA = 'NO_DATA_ERROR',
  BAD_REQUEST = 'BAD_REQUEST_ERROR',
  FORBIDDEN = 'FORBIDDEN_ERROR',
  DATA_EXISTS = 'DATA_EXISTS_ERROR',
  PAYMENT_ERROR = 'PAYMENT_ERROR',
}
